package duke.js;

import duke.js.Analyzer.FuncInfo;
import duke.js.Analyzer.Scope;
import duke.js.Analyzer.Var;
import duke.js.Node.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Turns one analyzed JavaScript module into one Java class that dukec then compiles with the rest of
 * the kernel. Every JS value is an {@code Object}; operators and property access are calls into
 * {@code duke.js.rt.JS}.
 *
 * <ul>
 *   <li>Top-level variables become static fields. Other variables are Java locals, or one-element
 *       arrays ("cells") when a closure captures them, since Java lambdas need effectively final
 *       variables. Cells are created where the variable's scope starts, so each loop iteration of a
 *       {@code let} gets a fresh one, as JavaScript requires.
 *   <li>Functions are lambdas. Java forbids a lambda parameter or local to shadow an enclosing one,
 *       so every generated name carries a unique number.
 *   <li>{@code return}, {@code break} and {@code continue} are guarded by {@code if (JS.T)}, so javac
 *       never rejects the statements JavaScript lets follow them.
 * </ul>
 */
final class JavaGen {

    /** Globals the runtime defines; other undeclared names are compile errors. */
    static final Set<String> GLOBALS = Set.of("console", "Math", "String", "Number", "Array", "Object", "parseInt",
            "Kernel");

    static final String PACKAGE = "duke.js.gen";

    private final String file;
    private final Analyzer an;
    private final String className;
    private final Map<Var, String> names = new IdentityHashMap<>();
    /** While generating a for-loop body, the per-iteration copy of each captured loop variable. */
    private final Map<Var, String> copies = new IdentityHashMap<>();
    /** One entry per enclosing loop: the label to break out of the body for {@code continue}, or null. */
    private final Deque<String> continueLabels = new ArrayDeque<>();
    private StringBuilder out = new StringBuilder();
    private List<String> temps = new ArrayList<>();
    private FuncInfo fn;
    private int indent;
    private int uid;

    JavaGen(String file, Analyzer an, String className) {
        this.file = file;
        this.an = an;
        this.className = className;
    }

    String generate(List<Stmt> program) {
        fn = an.main();
        indent = 2;
        List<String> fields = new ArrayList<>();
        for (Var v : an.globals) {
            names.put(v, "g_" + v.name);
            fields.add("    static Object g_" + v.name + ";\n");
        }
        for (Var v : an.globals) {
            if (v.declared != null) {
                line(names.get(v) + " = " + function(v.declared) + ";");
            }
        }
        for (Stmt s : program) {
            stmt(s);
        }
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(PACKAGE).append(";\n\n");
        sb.append("import duke.js.rt.JS;\n");
        sb.append("import duke.js.rt.Modules;\n\n");
        sb.append("/** Generated by jsc from ").append(file.replace('\\', '/')).append(". Do not edit. */\n");
        sb.append("public final class ").append(className).append(" {\n\n");
        sb.append("    private ").append(className).append("() {\n    }\n\n");
        // dukec initializes everything in this package at boot, which signs the module up to be run.
        sb.append("    static {\n        Modules.register(() -> run());\n    }\n\n");
        fields.forEach(sb::append);
        sb.append("\n    public static void run() {\n");
        declareTemps(sb, "        ");
        sb.append(out);
        sb.append("    }\n}\n");
        return sb.toString();
    }

    // ---- output ----

    private void line(String text) {
        out.append("    ".repeat(indent)).append(text).append('\n');
    }

    private void declareTemps(StringBuilder sb, String pad) {
        if (!temps.isEmpty()) {
            sb.append(pad).append("Object ").append(String.join(" = null, ", temps)).append(" = null;\n");
        }
    }

    /** Numbered across the whole module: Java forbids a lambda's locals to reuse a name from the enclosing method. */
    private String newTemp() {
        String t = "t" + ++uid;
        temps.add(t);
        return t;
    }

    private static String quote(String s) {
        StringBuilder sb = new StringBuilder("\"");
        for (char c : s.toCharArray()) {
            switch (c) {
                case '"' -> sb.append("\\\"");
                case '\\' -> sb.append("\\\\");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> {
                    if (c < ' ' || c > '~') {
                        sb.append(String.format("\\u%04x", (int) c));
                    } else {
                        sb.append(c);
                    }
                }
            }
        }
        return sb.append('"').toString();
    }

    // ---- variables ----

    private static boolean isCell(Var v) {
        return v.boxed() && !v.kind.equals("this") && !v.kind.equals("self");
    }

    private String name(Var v) {
        String copy = copies.get(v);
        if (copy != null) {
            return copy;
        }
        String n = names.get(v);
        if (n == null) {
            n = "v" + ++uid + "_" + v.name;
            names.put(v, n);
        }
        return n;
    }

    private String read(Var v) {
        return isCell(v) && !v.global ? name(v) + "[0]" : name(v);
    }

    /** A Java assignment expression storing {@code value} into {@code v}. */
    private String write(Var v, String value) {
        return "(" + store(v, value) + ")";
    }

    /** The same without parentheses, which is what a statement needs. */
    private String store(Var v, String value) {
        return read(v) + " = " + value;
    }

    private void declare(Var v, String init) {
        if (isCell(v)) {
            line("final Object[] " + name(v) + " = { " + init + " };");
        } else {
            line("Object " + name(v) + " = " + init + ";");
        }
    }

    /** Declares the Java locals of a scope; parameters, {@code this} and the function's own name are declared elsewhere. */
    private void declareLocals(Scope scope) {
        if (scope.topLevel) {
            return;
        }
        for (Var v : scope.vars.values()) {
            if (!v.kind.equals("this") && !v.kind.equals("self") && !v.kind.equals("param")) {
                declare(v, "null");
            }
        }
    }

    private void hoist(Scope scope) {
        for (FunctionDecl d : scope.hoisted) {
            if (!scope.topLevel) {
                line(store(an.resolved.get(d), function(d.function())) + ";");
            }
        }
    }

    // ---- functions ----

    private String function(Function f) {
        FuncInfo info = an.functions.get(f);
        int id = ++uid;
        String callee = "callee" + id;
        String self = "self" + id;
        String args = "args" + id;

        StringBuilder savedOut = out;
        List<String> savedTemps = temps;
        FuncInfo savedFn = fn;
        Deque<String> savedLoops = new ArrayDeque<>(continueLabels);
        out = new StringBuilder();
        temps = new ArrayList<>();
        fn = info;
        continueLabels.clear();
        indent++;

        for (Var v : info.scope.vars.values()) {
            if (v.kind.equals("this")) {
                names.put(v, self);
            } else if (v.kind.equals("self")) {
                names.put(v, callee);
            }
        }
        for (int i = 0; i < f.params().size(); i++) {
            declare(info.scope.vars.get(f.params().get(i)), "JS.arg(" + args + ", " + i + ")");
        }
        declareLocals(info.scope);
        hoist(info.scope);
        for (Stmt s : f.body()) {
            stmt(s);
        }
        line("return JS.U;");

        StringBuilder body = new StringBuilder();
        declareTemps(body, "    ".repeat(indent));
        body.append(out);
        indent--;
        out = savedOut;
        temps = savedTemps;
        fn = savedFn;
        continueLabels.clear();
        continueLabels.addAll(savedLoops);
        return "JS.fn(" + quote(f.name() == null ? "" : f.name()) + ", (" + callee + ", " + self + ", " + args
                + ") -> {\n" + body + "    ".repeat(indent) + "})";
    }

    // ---- statements ----

    private void stmt(Stmt s) {
        switch (s) {
            case VarDecl d -> {
                for (Declarator decl : d.declarators()) {
                    Var v = an.resolved.get(decl);
                    if (decl.init() != null) {
                        line(store(v, expr(decl.init())) + ";");
                    } else if (!d.kind().equals("var")) {
                        line(store(v, "JS.U") + ";");
                    }
                }
            }
            case ExprStmt e -> exprStatement(e.expr());
            case If i -> {
                line("if (" + cond(i.test()) + ") {");
                body(i.then());
                if (i.otherwise() != null) {
                    line("} else {");
                    body(i.otherwise());
                }
                line("}");
            }
            case While w -> {
                line("while (" + cond(w.test()) + ") {");
                continueLabels.push("");
                body(w.body());
                continueLabels.pop();
                line("}");
            }
            case DoWhile w -> {
                line("do {");
                continueLabels.push("");
                body(w.body());
                continueLabels.pop();
                line("} while (" + cond(w.test()) + ");");
            }
            case For f -> genFor(f);
            case ForOf f -> genForOf(f);
            case Block b -> {
                line("{");
                indent++;
                Scope scope = an.scopes.get(b);
                declareLocals(scope);
                hoist(scope);
                b.body().forEach(this::stmt);
                indent--;
                line("}");
            }
            case Return r -> {
                String value = r.value() == null ? "JS.U" : expr(r.value());
                line(fn.main ? "if (JS.T) return;" : "if (JS.T) return " + value + ";");
            }
            case Break b -> line("if (JS.T) break;");
            case Continue c -> {
                String label = continueLabels.peek();
                line(label == null || label.isEmpty() ? "if (JS.T) continue;" : "if (JS.T) break " + label + ";");
            }
            case FunctionDecl d -> { }
            case Empty e -> { }
        }
    }

    /** A loop or branch body, braced so a single statement cannot leak a declaration. */
    private void body(Stmt s) {
        indent++;
        if (s instanceof Block) {
            // The block emits its own braces; unwrap them to keep the output flat.
            Block b = (Block) s;
            Scope scope = an.scopes.get(b);
            declareLocals(scope);
            hoist(scope);
            b.body().forEach(this::stmt);
        } else {
            stmt(s);
        }
        indent--;
    }

    private void exprStatement(Expr e) {
        if (e instanceof Update u) {
            if (u.target() instanceof Ident id) {
                Var v = assignable(id);
                line(store(v, (u.op().equals("++") ? "JS.add" : "JS.sub") + "(" + read(v) + ", JS.ONE)") + ";");
            } else {
                line(update(u, false) + ";");
            }
            return;
        }
        if (e instanceof Assign a && a.target() instanceof Ident id && !a.op().endsWith("&&=")
                && !a.op().equals("||=") && !a.op().equals("??=")) {
            Var v = assignable(id);
            String value = a.op().equals("=") ? expr(a.value())
                    : operator(a.op().substring(0, a.op().length() - 1)) + "(" + read(v) + ", " + expr(a.value()) + ")";
            line(store(v, value) + ";");
            return;
        }
        String text = expr(e);
        if (text.startsWith("JS.call(") || text.startsWith("JS.invoke(") || text.startsWith("JS.set(")) {
            line(text + ";");
        } else {
            line("JS.second(" + text + ", JS.U);");
        }
    }

    private int labels;

    private void genFor(For f) {
        Scope scope = an.scopes.get(f);
        line("{");
        indent++;
        declareLocals(scope);
        if (f.init() != null) {
            stmt(f.init());
        }
        line("for (;;) {");
        indent++;
        if (f.test() != null) {
            line("if (!(" + cond(f.test()) + ")) break;");
        }
        List<Var> captured = new ArrayList<>();
        for (Var v : scope.vars.values()) {
            if (isCell(v)) {
                captured.add(v);
            }
        }
        // A closure made in the body sees this iteration's copy of a captured loop variable.
        Map<Var, String> state = new IdentityHashMap<>();
        for (Var v : captured) {
            String copy = "it" + ++uid + "_" + v.name;
            state.put(v, name(v));
            line("final Object[] " + copy + " = { " + name(v) + "[0] };");
            copies.put(v, copy);
        }
        String label = "body" + ++labels;
        line(label + ": {");
        continueLabels.push(label);
        body(f.body());
        continueLabels.pop();
        line("}");
        for (Var v : captured) {
            line(state.get(v) + "[0] = " + copies.get(v) + "[0];");
            copies.remove(v);
        }
        if (f.update() != null) {
            exprStatement(f.update());
        }
        indent--;
        line("}");
        indent--;
        line("}");
    }

    private void genForOf(ForOf f) {
        Var v = an.resolved.get(f);
        Scope scope = an.scopes.get(f);
        String items = "items" + ++uid;
        String index = "i" + uid;
        line("{");
        indent++;
        line("final Object " + items + " = " + expr(f.iterable()) + ";");
        line("for (long " + index + " = 0; " + index + " < JS.length(" + items + "); " + index + "++) {");
        indent++;
        String element = "JS.getIndex(" + items + ", " + index + ")";
        if (scope.vars.containsKey(f.name()) && !v.global) {
            declare(v, element);
        } else {
            line(store(v, element) + ";");
        }
        continueLabels.push("");
        body(f.body());
        continueLabels.pop();
        indent--;
        line("}");
        indent--;
        line("}");
    }

    // ---- expressions ----

    /** A Java boolean expression for the truthiness of {@code e}. */
    private String cond(Expr e) {
        switch (e) {
            case Lit l when l.value() == Literal.TRUE -> {
                return "true";
            }
            case Lit l when l.value() == Literal.FALSE -> {
                return "false";
            }
            case Unary u when u.op().equals("!") -> {
                return "!" + cond(u.operand());
            }
            case Logical l when l.op().equals("&&") -> {
                return "(" + cond(l.left()) + " && " + cond(l.right()) + ")";
            }
            case Logical l when l.op().equals("||") -> {
                return "(" + cond(l.left()) + " || " + cond(l.right()) + ")";
            }
            case Binary b -> {
                String test = comparison(b);
                if (test != null) {
                    return test;
                }
            }
            default -> { }
        }
        return "JS.truthy(" + expr(e) + ")";
    }

    /** A Java boolean expression for a comparison, or null if {@code b} is not one. */
    private String comparison(Binary b) {
        String method = switch (b.op()) {
            case "<" -> "JS.lt";
            case ">" -> "JS.gt";
            case "<=" -> "JS.le";
            case ">=" -> "JS.ge";
            case "===", "!==" -> "JS.seq";
            case "==", "!=" -> "JS.leq";
            default -> null;
        };
        if (method == null) {
            return null;
        }
        String call = method + "(" + expr(b.left()) + ", " + expr(b.right()) + ")";
        return b.op().equals("!==") || b.op().equals("!=") ? "!" + call : call;
    }

    private static String operator(String op) {
        return switch (op) {
            case "+" -> "JS.add";
            case "-" -> "JS.sub";
            case "*" -> "JS.mul";
            case "/" -> "JS.div";
            case "%" -> "JS.mod";
            case "&" -> "JS.band";
            case "|" -> "JS.bor";
            case "^" -> "JS.bxor";
            case "<<" -> "JS.shl";
            case ">>" -> "JS.shr";
            case ">>>" -> "JS.ushr";
            case "**" -> "JS.pow";
            default -> throw new IllegalStateException("operator " + op);
        };
    }

    private String expr(Expr e) {
        switch (e) {
            case Num n -> {
                return "JS.n(" + n.value() + "L)";
            }
            case Str s -> {
                return quote(s.value());
            }
            case Lit l -> {
                return switch (l.value()) {
                    case TRUE -> "Boolean.TRUE";
                    case FALSE -> "Boolean.FALSE";
                    case NULL -> "JS.NULL";
                    case UNDEFINED -> "JS.U";
                };
            }
            case This t -> {
                Var v = an.resolved.get(t);
                return v == null ? "JS.U" : read(v);
            }
            case Ident id -> {
                Var v = an.resolved.get(id);
                return v == null ? "JS.global(" + quote(id.name()) + ")" : read(v);
            }
            case Template t -> {
                if (t.exprs().isEmpty()) {
                    return quote(t.chunks().get(0));
                }
                List<String> parts = new ArrayList<>();
                for (int i = 0; i < t.exprs().size(); i++) {
                    parts.add(quote(t.chunks().get(i)));
                    parts.add(expr(t.exprs().get(i)));
                }
                parts.add(quote(t.chunks().get(t.exprs().size())));
                return "JS.concat(" + String.join(", ", parts) + ")";
            }
            case ArrayLit a -> {
                return "JS.array(" + list(a.elements()) + ")";
            }
            case ObjectLit o -> {
                List<String> parts = new ArrayList<>();
                for (Property p : o.properties()) {
                    parts.add(quote(p.key()));
                    parts.add(expr(p.value()));
                }
                return "JS.object(" + String.join(", ", parts) + ")";
            }
            case FuncExpr f -> {
                return function(f.function());
            }
            case Unary u -> {
                return switch (u.op()) {
                    case "!" -> "JS.bool(!" + cond(u.operand()) + ")";
                    case "-" -> "JS.neg(" + expr(u.operand()) + ")";
                    case "+" -> "JS.plus(" + expr(u.operand()) + ")";
                    case "~" -> "JS.bnot(" + expr(u.operand()) + ")";
                    case "typeof" -> "JS.typeof(" + expr(u.operand()) + ")";
                    default -> throw error(u.line(), "unsupported operator " + u.op());
                };
            }
            case Update u -> {
                return update(u, true);
            }
            case Binary b -> {
                String test = comparison(b);
                if (test != null) {
                    return "JS.bool(" + test + ")";
                }
                return operator(b.op()) + "(" + expr(b.left()) + ", " + expr(b.right()) + ")";
            }
            case Logical l -> {
                String t = newTemp();
                String left = "(" + t + " = " + expr(l.left()) + ")";
                String right = expr(l.right());
                return switch (l.op()) {
                    case "&&" -> "(JS.truthy(" + left + ") ? (Object) " + right + " : " + t + ")";
                    case "||" -> "(JS.truthy(" + left + ") ? " + t + " : (Object) " + right + ")";
                    default -> "(JS.nullish(" + left + ") ? (Object) " + right + " : " + t + ")";
                };
            }
            case Assign a -> {
                return assign(a);
            }
            case Conditional c -> {
                return "(" + cond(c.test()) + " ? (Object) " + expr(c.then()) + " : (Object) " + expr(c.otherwise()) + ")";
            }
            case Call c -> {
                String args = list(c.args());
                String tail = args.isEmpty() ? "" : ", " + args;
                return switch (c.callee()) {
                    case Member m -> "JS.invoke(" + expr(m.object()) + ", " + quote(m.name()) + tail + ")";
                    case Index i -> "JS.invoke(" + expr(i.object()) + ", " + expr(i.index()) + tail + ")";
                    default -> "JS.call(" + expr(c.callee()) + tail + ")";
                };
            }
            case Member m -> {
                return "JS.get(" + expr(m.object()) + ", " + quote(m.name()) + ")";
            }
            case Index i -> {
                return "JS.get(" + expr(i.object()) + ", " + expr(i.index()) + ")";
            }
            case Sequence s -> {
                String result = expr(s.exprs().get(s.exprs().size() - 1));
                for (int i = s.exprs().size() - 2; i >= 0; i--) {
                    result = "JS.second(" + expr(s.exprs().get(i)) + ", " + result + ")";
                }
                return result;
            }
        }
    }

    private String list(List<Expr> exprs) {
        List<String> parts = new ArrayList<>();
        for (Expr e : exprs) {
            parts.add(expr(e));
        }
        return String.join(", ", parts);
    }

    private Var assignable(Ident id) {
        Var v = an.resolved.get(id);
        if (v == null) {
            throw error(id.line(), "cannot assign to " + id.name());
        }
        if (v.kind.equals("const")) {
            throw error(id.line(), "Assignment to constant variable '" + id.name() + "'");
        }
        if (v.kind.equals("this") || v.kind.equals("self")) {
            throw error(id.line(), "cannot assign to " + id.name());
        }
        return v;
    }

    private String update(Update u, boolean valueNeeded) {
        String op = u.op().equals("++") ? "JS.add" : "JS.sub";
        boolean postfix = !u.prefix() && valueNeeded;
        switch (u.target()) {
            case Ident id -> {
                Var v = assignable(id);
                if (!postfix) {
                    return write(v, op + "(" + read(v) + ", JS.ONE)");
                }
                String old = newTemp();
                return "JS.second(" + write(v, op + "(" + old + " = " + read(v) + ", JS.ONE)") + ", " + old + ")";
            }
            case Member m -> {
                return referenceUpdate(m.object(), quote(m.name()), op, "JS.ONE", postfix);
            }
            case Index i -> {
                return referenceUpdate(i.object(), expr(i.index()), op, "JS.ONE", postfix);
            }
            default -> throw error(u.line(), "invalid increment target");
        }
    }

    /** {@code o[k] = op(o[k], value)}, evaluating o and k once; yields the old value when {@code postfix}. */
    private String referenceUpdate(Expr object, String key, String op, String value, boolean postfix) {
        String o = newTemp();
        String k = newTemp();
        if (!postfix) {
            return "JS.set(" + o + " = " + expr(object) + ", " + k + " = " + key + ", " + op + "(JS.get(" + o + ", "
                    + k + "), " + value + "))";
        }
        String old = newTemp();
        return "JS.second(JS.set(" + o + " = " + expr(object) + ", " + k + " = " + key + ", " + op + "(" + old
                + " = JS.get(" + o + ", " + k + "), " + value + ")), " + old + ")";
    }

    private String assign(Assign a) {
        String op = a.op();
        switch (a.target()) {
            case Ident id -> {
                Var v = assignable(id);
                if (op.equals("=")) {
                    return write(v, expr(a.value()));
                }
                if (op.equals("&&=") || op.equals("||=") || op.equals("??=")) {
                    String test = switch (op) {
                        case "&&=" -> "JS.truthy(" + read(v) + ")";
                        case "||=" -> "!JS.truthy(" + read(v) + ")";
                        default -> "JS.nullish(" + read(v) + ")";
                    };
                    return "(" + test + " ? " + write(v, expr(a.value())) + " : " + read(v) + ")";
                }
                return write(v, operator(op.substring(0, op.length() - 1)) + "(" + read(v) + ", " + expr(a.value()) + ")");
            }
            case Member m -> {
                return assignReference(a, m.object(), quote(m.name()));
            }
            case Index i -> {
                return assignReference(a, i.object(), expr(i.index()));
            }
            default -> throw error(a.line(), "invalid assignment target");
        }
    }

    private String assignReference(Assign a, Expr object, String key) {
        if (a.op().equals("=")) {
            return "JS.set(" + expr(object) + ", " + key + ", " + expr(a.value()) + ")";
        }
        if (a.op().equals("&&=") || a.op().equals("||=") || a.op().equals("??=")) {
            throw error(a.line(), "logical assignment is only supported on plain variables");
        }
        String op = operator(a.op().substring(0, a.op().length() - 1));
        return referenceUpdate(object, key, op, expr(a.value()), false);
    }

    private JsException error(int line, String message) {
        return new JsException(file, line, message);
    }
}
