package duke.js;

import duke.js.Analyzer.FuncInfo;
import duke.js.Analyzer.Scope;
import duke.js.Analyzer.Var;
import duke.js.Node.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Turns one analyzed JavaScript module into one Java class that dukec then compiles with the rest of
 * the kernel. Every JS value is an {@code Object}; operators and property access are calls into
 * {@code duke.js.rt.JS}.
 *
 * <ul>
 *   <li>Top-level variables become static fields. Other variables are Java locals, or one-element
 *       arrays ("cells") when a closure captures them, since Java lambdas need effectively final
 *       variables. Cells are created where the variable's scope starts, so each loop iteration of a
 *       {@code let} gets a fresh one, as JavaScript requires.
 *   <li>Functions are lambdas. Java forbids a lambda parameter or local to shadow an enclosing one,
 *       so every generated name carries a unique number.
 *   <li>{@code return}, {@code break} and {@code continue} are guarded by {@code if (JS.T)}, so javac
 *       never rejects the statements JavaScript lets follow them.
 * </ul>
 */
final class JavaGen {

    /** Globals the runtime defines; other undeclared names are compile errors. */
    static final Set<String> GLOBALS = Set.of("console", "Math", "String", "Number", "Array", "Object", "Function",
            "parseInt", "Kernel", "Error", "TypeError", "RangeError", "ReferenceError", "SyntaxError", "EvalError",
            "URIError");

    static final String PACKAGE = "duke.js.gen";

    private final String file;
    private final Analyzer an;
    private final String className;
    private final Map<Var, String> names = new IdentityHashMap<>();
    /** While generating a for-loop body, the per-iteration copy of each captured loop variable. */
    private final Map<Var, String> copies = new IdentityHashMap<>();
    /** One entry per enclosing loop: the label to break out of the body for {@code continue}, or null. */
    private final Deque<String> continueLabels = new ArrayDeque<>();
    /** Labels in scope, innermost first, with the Java statements that break out of or continue each one. */
    private final Deque<Target> targets = new ArrayDeque<>();
    /** Labels written directly before the loop that is about to be generated. */
    private final List<String> pendingLabels = new ArrayList<>();

    private record Target(String name, String breakStatement, String continueStatement) {}

    /** The Java label put on a loop that has JavaScript labels, and how many targets it registered. */
    private record Loop(String javaLabel, int registered) {}
    private StringBuilder out = new StringBuilder();
    private List<String> temps = new ArrayList<>();
    private FuncInfo fn;
    /** The name of the Java variable holding the current function's arguments array. */
    private String currentArgs;
    private int indent;
    private int uid;

    JavaGen(String file, Analyzer an, String className) {
        this.file = file;
        this.an = an;
        this.className = className;
    }

    String generate(List<Stmt> program) {
        fn = an.main();
        indent = 2;
        List<String> fields = new ArrayList<>();
        for (Var v : an.globals) {
            names.put(v, "g_" + v.name);
            fields.add("    static Object g_" + v.name + ";\n");
        }
        for (Var v : an.globals) {
            if (v.declared != null) {
                line(names.get(v) + " = " + function(v.declared) + ";");
            }
        }
        for (Stmt s : program) {
            stmt(s);
        }
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(PACKAGE).append(";\n\n");
        sb.append("import duke.js.rt.JS;\n");
        sb.append("import duke.js.rt.Modules;\n\n");
        sb.append("/** Generated by jsc from ").append(file.replace('\\', '/')).append(". Do not edit. */\n");
        sb.append("public final class ").append(className).append(" {\n\n");
        sb.append("    private ").append(className).append("() {\n    }\n\n");
        // dukec initializes everything in this package at boot, which signs the module up to be run.
        sb.append("    static {\n        Modules.register(() -> run());\n    }\n\n");
        fields.forEach(sb::append);
        sb.append("\n    public static void run() {\n");
        declareTemps(sb, "        ");
        sb.append(out);
        sb.append("    }\n}\n");
        return sb.toString();
    }

    // ---- output ----

    private void line(String text) {
        out.append("    ".repeat(indent)).append(text).append('\n');
    }

    private void declareTemps(StringBuilder sb, String pad) {
        if (!temps.isEmpty()) {
            sb.append(pad).append("Object ").append(String.join(" = null, ", temps)).append(" = null;\n");
        }
    }

    /** Numbered across the whole module: Java forbids a lambda's locals to reuse a name from the enclosing method. */
    private String newTemp() {
        String t = "t" + ++uid;
        temps.add(t);
        return t;
    }

    private static String quote(String s) {
        StringBuilder sb = new StringBuilder("\"");
        for (char c : s.toCharArray()) {
            switch (c) {
                case '"' -> sb.append("\\\"");
                case '\\' -> sb.append("\\\\");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> {
                    if (c < ' ' || c > '~') {
                        sb.append(String.format("\\u%04x", (int) c));
                    } else {
                        sb.append(c);
                    }
                }
            }
        }
        return sb.append('"').toString();
    }

    // ---- variables ----

    private static boolean isCell(Var v) {
        return v.boxed() && !v.kind.equals("this") && !v.kind.equals("self");
    }

    private String name(Var v) {
        String copy = copies.get(v);
        if (copy != null) {
            return copy;
        }
        String n = names.get(v);
        if (n == null) {
            n = "v" + ++uid + "_" + v.name;
            names.put(v, n);
        }
        return n;
    }

    private String read(Var v) {
        return isCell(v) && !v.global ? name(v) + "[0]" : name(v);
    }

    /** A Java assignment expression storing {@code value} into {@code v}. */
    private String write(Var v, String value) {
        return "(" + store(v, value) + ")";
    }

    /** The same without parentheses, which is what a statement needs. */
    private String store(Var v, String value) {
        return read(v) + " = " + value;
    }

    private void declare(Var v, String init) {
        if (isCell(v)) {
            line("final Object[] " + name(v) + " = { " + init + " };");
        } else {
            line("Object " + name(v) + " = " + init + ";");
        }
    }

    /** Declares the Java locals of a scope; parameters, {@code this} and the function's own name are declared elsewhere. */
    private void declareLocals(Scope scope) {
        if (scope.topLevel) {
            return;
        }
        for (Var v : scope.vars.values()) {
            if (!v.kind.equals("this") && !v.kind.equals("self") && !v.kind.equals("param")
                    && !v.kind.equals("arguments")) {
                declare(v, "null");
            }
        }
    }

    private void hoist(Scope scope) {
        for (FunctionDecl d : scope.hoisted) {
            if (!scope.topLevel) {
                line(store(an.resolved.get(d), function(d.function())) + ";");
            }
        }
    }

    // ---- functions ----

    private String function(Function f) {
        return function(f, f.name());
    }

    /** An anonymous function bound to a name takes that name, as in JavaScript ({@code const f = () => 1}). */
    private String named(Expr e, String hint) {
        if (e instanceof FuncExpr fe && fe.function().name() == null) {
            return function(fe.function(), hint);
        }
        return expr(e);
    }

    private String function(Function f, String name) {
        FuncInfo info = an.functions.get(f);
        int id = ++uid;
        String callee = "callee" + id;
        String self = "self" + id;
        String args = "args" + id;

        StringBuilder savedOut = out;
        List<String> savedTemps = temps;
        FuncInfo savedFn = fn;
        Deque<String> savedLoops = new ArrayDeque<>(continueLabels);
        Deque<Target> savedTargets = new ArrayDeque<>(targets);
        targets.clear();
        String savedArgs = currentArgs;
        currentArgs = args;
        out = new StringBuilder();
        temps = new ArrayList<>();
        fn = info;
        continueLabels.clear();
        indent++;

        for (Var v : info.scope.vars.values()) {
            if (v.kind.equals("this")) {
                names.put(v, self);
            } else if (v.kind.equals("self")) {
                names.put(v, callee);
            } else if (v.kind.equals("arguments")) {
                declare(v, "JS.arguments(" + args + ")");
            }
        }
        for (int i = 0; i < f.params().size(); i++) {
            declare(info.scope.vars.get(f.params().get(i)), "JS.arg(" + args + ", " + i + ")");
        }
        declareLocals(info.scope);
        hoist(info.scope);
        for (Stmt s : f.body()) {
            stmt(s);
        }
        line("return JS.U;");

        StringBuilder body = new StringBuilder();
        declareTemps(body, "    ".repeat(indent));
        body.append(out);
        indent--;
        out = savedOut;
        temps = savedTemps;
        fn = savedFn;
        continueLabels.clear();
        continueLabels.addAll(savedLoops);
        targets.clear();
        targets.addAll(savedTargets);
        currentArgs = savedArgs;
        return (f.arrow() ? "JS.arrow(" : "JS.fn(") + quote(name == null ? "" : name) + ", (" + callee + ", " + self + ", " + args
                + ") -> {\n" + body + "    ".repeat(indent) + "})";
    }

    // ---- statements ----

    private void stmt(Stmt s) {
        switch (s) {
            case VarDecl d -> {
                for (Declarator decl : d.declarators()) {
                    Var v = an.resolved.get(decl);
                    if (decl.init() != null) {
                        line(store(v, named(decl.init(), decl.name())) + ";");
                    } else if (!d.kind().equals("var")) {
                        line(store(v, "JS.U") + ";");
                    }
                }
            }
            case ExprStmt e -> exprStatement(e.expr());
            case If i -> {
                line("if (" + cond(i.test()) + ") {");
                body(i.then());
                if (i.otherwise() != null) {
                    line("} else {");
                    body(i.otherwise());
                }
                line("}");
            }
            case While w -> {
                Loop loop = enterLoop(null);
                line(prefix(loop) + "while (" + cond(w.test()) + ") {");
                continueLabels.push("");
                body(w.body());
                continueLabels.pop();
                line("}");
                exitLoop(loop);
            }
            case DoWhile w -> {
                Loop loop = enterLoop(null);
                line(prefix(loop) + "do {");
                continueLabels.push("");
                body(w.body());
                continueLabels.pop();
                line("} while (" + cond(w.test()) + ");");
                exitLoop(loop);
            }
            case Labeled l -> genLabeled(l);
            case Switch sw -> genSwitch(sw);
            case For f -> genFor(f);
            case ForOf f -> genForOf(f);
            case Block b -> {
                line("{");
                indent++;
                Scope scope = an.scopes.get(b);
                declareLocals(scope);
                hoist(scope);
                b.body().forEach(this::stmt);
                indent--;
                line("}");
            }
            case Return r -> {
                String value = r.value() == null ? "JS.U" : expr(r.value());
                line(fn.main ? "if (JS.T) return;" : "if (JS.T) return " + value + ";");
            }
            case Throw t -> line("if (JS.T) throw JS.thrown(" + expr(t.value()) + ");");
            case Try t -> genTry(t);
            case Break b -> line("if (JS.T) " + (b.label() == null ? "break;" : target(b.label(), b.line()).breakStatement()));
            case Continue c -> {
                if (c.label() != null) {
                    String jump = target(c.label(), c.line()).continueStatement();
                    if (jump == null) {
                        throw error(c.line(), "illegal continue: '" + c.label() + "' does not label a loop");
                    }
                    line("if (JS.T) " + jump);
                } else {
                    String label = continueLabels.peek();
                    line(label == null || label.isEmpty() ? "if (JS.T) continue;" : "if (JS.T) break " + label + ";");
                }
            }
            case FunctionDecl d -> { }
            case Empty e -> { }
        }
    }

    /** A loop or branch body, braced so a single statement cannot leak a declaration. */
    private void body(Stmt s) {
        indent++;
        if (s instanceof Block) {
            // The block emits its own braces; unwrap them to keep the output flat.
            Block b = (Block) s;
            Scope scope = an.scopes.get(b);
            declareLocals(scope);
            hoist(scope);
            b.body().forEach(this::stmt);
        } else {
            stmt(s);
        }
        indent--;
    }

    private void exprStatement(Expr e) {
        if (e instanceof Update u) {
            if (u.target() instanceof Ident id) {
                Var v = assignable(id);
                line(store(v, (u.op().equals("++") ? "JS.add" : "JS.sub") + "(" + read(v) + ", JS.ONE)") + ";");
            } else {
                line(update(u, false) + ";");
            }
            return;
        }
        if (e instanceof Assign a && a.target() instanceof Ident id && !a.op().endsWith("&&=")
                && !a.op().equals("||=") && !a.op().equals("??=")) {
            Var v = assignable(id);
            String value = a.op().equals("=") ? named(a.value(), id.name())
                    : operator(a.op().substring(0, a.op().length() - 1)) + "(" + read(v) + ", " + expr(a.value()) + ")";
            line(store(v, value) + ";");
            return;
        }
        String text = expr(e);
        if (text.startsWith("JS.call(") || text.startsWith("JS.invoke(") || text.startsWith("JS.set(")) {
            line(text + ";");
        } else {
            line("JS.second(" + text + ", JS.U);");
        }
    }

    private int labels;

    private void genFor(For f) {
        Scope scope = an.scopes.get(f);
        line("{");
        indent++;
        declareLocals(scope);
        if (f.init() != null) {
            stmt(f.init());
        }
        String label = "body" + ++labels;
        Loop loop = enterLoop("break " + label + ";");
        line(prefix(loop) + "for (;;) {");
        indent++;
        if (f.test() != null) {
            line("if (!(" + cond(f.test()) + ")) break;");
        }
        List<Var> captured = new ArrayList<>();
        for (Var v : scope.vars.values()) {
            if (isCell(v)) {
                captured.add(v);
            }
        }
        // A closure made in the body sees this iteration's copy of a captured loop variable.
        Map<Var, String> state = new IdentityHashMap<>();
        for (Var v : captured) {
            String copy = "it" + ++uid + "_" + v.name;
            state.put(v, name(v));
            line("final Object[] " + copy + " = { " + name(v) + "[0] };");
            copies.put(v, copy);
        }
        line(label + ": {");
        continueLabels.push(label);
        body(f.body());
        continueLabels.pop();
        line("}");
        for (Var v : captured) {
            line(state.get(v) + "[0] = " + copies.get(v) + "[0];");
            copies.remove(v);
        }
        if (f.update() != null) {
            exprStatement(f.update());
        }
        indent--;
        line("}");
        exitLoop(loop);
        indent--;
        line("}");
    }

    private void genTry(Try t) {
        line("try {");
        body(t.block());
        if (t.handler() != null) {
            String exception = "ex" + ++uid;
            // Runtime errors and JavaScript throws are RuntimeExceptions; a stack overflow is an Error that
            // JavaScript can catch too (as a RangeError).
            line("} catch (RuntimeException | StackOverflowError " + exception + ") {");
            indent++;
            if (t.param() != null) {
                declare(an.resolved.get(t), "JS.caught(" + exception + ")");
            }
            indent--;
            body(t.handler());
        }
        if (t.finalizer() != null) {
            line("} finally {");
            body(t.finalizer());
        }
        line("}");
    }

    private void genForOf(ForOf f) {
        Var v = an.resolved.get(f);
        Scope scope = an.scopes.get(f);
        String items = "items" + ++uid;
        String index = "i" + uid;
        line("{");
        indent++;
        line("final Object " + items + " = " + (f.in() ? "JS.forInKeys(" + expr(f.iterable()) + ")" : expr(f.iterable()))
                + ";");
        Loop loop = enterLoop(null);
        line(prefix(loop) + "for (long " + index + " = 0; " + index + " < JS.length(" + items + "); " + index + "++) {");
        indent++;
        String element = "JS.getIndex(" + items + ", " + index + ")";
        if (scope.vars.containsKey(f.name()) && !v.global) {
            declare(v, element);
        } else {
            line(store(v, element) + ";");
        }
        continueLabels.push("");
        body(f.body());
        continueLabels.pop();
        indent--;
        line("}");
        exitLoop(loop);
        indent--;
        line("}");
    }

    /** Takes the labels waiting for this loop and registers them; null continue statement means "continue javaLabel". */
    private Loop enterLoop(String continueStatement) {
        if (pendingLabels.isEmpty()) {
            return new Loop(null, 0);
        }
        String javaLabel = "L" + ++uid;
        for (String name : pendingLabels) {
            targets.push(new Target(name, "break " + javaLabel + ";",
                    continueStatement == null ? "continue " + javaLabel + ";" : continueStatement));
        }
        int count = pendingLabels.size();
        pendingLabels.clear();
        return new Loop(javaLabel, count);
    }

    private void exitLoop(Loop loop) {
        for (int i = 0; i < loop.registered(); i++) {
            targets.pop();
        }
    }

    private static String prefix(Loop loop) {
        return loop.javaLabel() == null ? "" : loop.javaLabel() + ": ";
    }

    private Target target(String label, int line) {
        for (Target t : targets) {
            if (t.name().equals(label)) {
                return t;
            }
        }
        throw error(line, "undefined label '" + label + "'");
    }

    private void genLabeled(Labeled l) {
        Stmt inner = l.body();
        if (inner instanceof While || inner instanceof DoWhile || inner instanceof For || inner instanceof ForOf
                || inner instanceof Labeled) {
            pendingLabels.add(l.label());
            stmt(inner);
            return;
        }
        // Any other statement can only be left with a labeled break, which Java has for blocks.
        String javaLabel = "L" + ++uid;
        line(javaLabel + ": {");
        indent++;
        targets.push(new Target(l.label(), "break " + javaLabel + ";", null));
        stmt(inner);
        targets.pop();
        indent--;
        line("}");
    }

    /**
     * A switch becomes: pick the matching clause's index by testing the cases in order (the default last,
     * wherever it was written), then a Java switch on that index, whose clauses fall through as JavaScript's do.
     */
    private void genSwitch(Switch sw) {
        Scope scope = an.scopes.get(sw);
        String value = "d" + ++uid;
        String chosen = "sw" + uid;
        line("{");
        indent++;
        declareLocals(scope);
        hoist(scope);
        line("final Object " + value + " = " + expr(sw.discriminant()) + ";");
        line("int " + chosen + " = -1;");
        int defaultIndex = -1;
        boolean first = true;
        for (int i = 0; i < sw.cases().size(); i++) {
            Case c = sw.cases().get(i);
            if (c.test() == null) {
                defaultIndex = i;
                continue;
            }
            line((first ? "if" : "else if") + " (JS.seq(" + value + ", " + expr(c.test()) + ")) " + chosen + " = " + i + ";");
            first = false;
        }
        line((first ? "" : "else ") + chosen + " = " + defaultIndex + ";");
        line("switch (" + chosen + ") {");
        indent++;
        for (int i = 0; i < sw.cases().size(); i++) {
            line("case " + i + ":");
            indent++;
            sw.cases().get(i).body().forEach(this::stmt);
            indent--;
        }
        indent--;
        line("}");
        indent--;
        line("}");
    }

    // ---- expressions ----

    /** A Java boolean expression for the truthiness of {@code e}. */
    private String cond(Expr e) {
        switch (e) {
            case Lit l when l.value() == Literal.TRUE -> {
                return "true";
            }
            case Lit l when l.value() == Literal.FALSE -> {
                return "false";
            }
            case Unary u when u.op().equals("!") -> {
                return "!" + cond(u.operand());
            }
            case Logical l when l.op().equals("&&") -> {
                return "(" + cond(l.left()) + " && " + cond(l.right()) + ")";
            }
            case Logical l when l.op().equals("||") -> {
                return "(" + cond(l.left()) + " || " + cond(l.right()) + ")";
            }
            case Binary b -> {
                String test = comparison(b);
                if (test != null) {
                    return test;
                }
            }
            default -> { }
        }
        return "JS.truthy(" + expr(e) + ")";
    }

    /** A Java boolean expression for a comparison, or null if {@code b} is not one. */
    private String comparison(Binary b) {
        String method = switch (b.op()) {
            case "<" -> "JS.lt";
            case ">" -> "JS.gt";
            case "<=" -> "JS.le";
            case ">=" -> "JS.ge";
            case "===", "!==" -> "JS.seq";
            case "==", "!=" -> "JS.leq";
            case "instanceof" -> "JS.instanceOf";
            case "in" -> "JS.in";
            default -> null;
        };
        if (method == null) {
            return null;
        }
        String call = method + "(" + expr(b.left()) + ", " + expr(b.right()) + ")";
        return b.op().equals("!==") || b.op().equals("!=") ? "!" + call : call;
    }

    private static String operator(String op) {
        return switch (op) {
            case "+" -> "JS.add";
            case "-" -> "JS.sub";
            case "*" -> "JS.mul";
            case "/" -> "JS.div";
            case "%" -> "JS.mod";
            case "&" -> "JS.band";
            case "|" -> "JS.bor";
            case "^" -> "JS.bxor";
            case "<<" -> "JS.shl";
            case ">>" -> "JS.shr";
            case ">>>" -> "JS.ushr";
            case "**" -> "JS.pow";
            default -> throw new IllegalStateException("operator " + op);
        };
    }

    private String expr(Expr e) {
        switch (e) {
            case Num n -> {
                return "JS.n(" + n.value() + "L)";
            }
            case Str s -> {
                return quote(s.value());
            }
            case Lit l -> {
                return switch (l.value()) {
                    case TRUE -> "Boolean.TRUE";
                    case FALSE -> "Boolean.FALSE";
                    case NULL -> "JS.NULL";
                    case UNDEFINED -> "JS.U";
                };
            }
            case This t -> {
                Var v = an.resolved.get(t);
                return v == null ? "JS.U" : read(v);
            }
            case Ident id -> {
                Var v = an.resolved.get(id);
                return v == null ? "JS.global(" + quote(id.name()) + ")" : read(v);
            }
            case Template t -> {
                if (t.exprs().isEmpty()) {
                    return quote(t.chunks().get(0));
                }
                List<String> parts = new ArrayList<>();
                for (int i = 0; i < t.exprs().size(); i++) {
                    parts.add(quote(t.chunks().get(i)));
                    parts.add(expr(t.exprs().get(i)));
                }
                parts.add(quote(t.chunks().get(t.exprs().size())));
                return "JS.concat(" + String.join(", ", parts) + ")";
            }
            case ArrayLit a -> {
                return "JS.array(" + list(a.elements()) + ")";
            }
            case ObjectLit o -> {
                List<String> parts = new ArrayList<>();
                boolean spreads = false;
                for (Property p : o.properties()) {
                    if (p.key() == null && p.computed() == null) {
                        spreads = true;
                        parts.add("JS.spreadOf(" + expr(((Spread) p.value()).value()) + ")");
                    } else if (p.computed() != null) {
                        parts.add(expr(p.computed()));
                        parts.add(expr(p.value()));
                    } else {
                        parts.add(quote(p.key()));
                        parts.add(named(p.value(), p.key()));
                    }
                }
                return (spreads ? "JS.objectSpread(" : "JS.object(") + String.join(", ", parts) + ")";
            }
            case Spread sp -> throw error(sp.line(), "unexpected spread: it can only appear in a call, an array or an object literal");
            case TaggedTemplate tt -> {
                String strings = "JS.templateStrings(new String[] {" + joinQuoted(tt.cooked()) + "}, new String[] {"
                        + joinQuoted(tt.raw()) + "})";
                String subs = list(tt.exprs());
                String tail = ", " + strings + (subs.isEmpty() ? "" : ", " + subs);
                return switch (tt.tag()) {
                    case Member m -> "JS.invoke(" + expr(m.object()) + ", " + quote(m.name()) + tail + ")";
                    case Index i -> "JS.invoke(" + expr(i.object()) + ", " + expr(i.index()) + tail + ")";
                    default -> "JS.call(" + expr(tt.tag()) + tail + ")";
                };
            }
            case Internal in -> {
                if (in.name().equals("restArgs")) {
                    return "JS.restArgs(" + currentArgs + ", " + ((Num) in.args().get(0)).value() + ")";
                }
                throw new IllegalStateException("internal " + in.name());
            }
            case FuncExpr f -> {
                return function(f.function());
            }
            case Unary u -> {
                return switch (u.op()) {
                    case "!" -> "JS.bool(!" + cond(u.operand()) + ")";
                    case "-" -> "JS.neg(" + expr(u.operand()) + ")";
                    case "+" -> "JS.plus(" + expr(u.operand()) + ")";
                    case "~" -> "JS.bnot(" + expr(u.operand()) + ")";
                    case "typeof" -> "JS.typeof(" + expr(u.operand()) + ")";
                    case "void" -> "JS.second(" + expr(u.operand()) + ", JS.U)";
                    case "delete" -> switch (u.operand()) {
                        case Member m -> "JS.delete(" + expr(m.object()) + ", " + quote(m.name()) + ")";
                        case Index i -> "JS.delete(" + expr(i.object()) + ", " + expr(i.index()) + ")";
                        default -> "JS.second(" + expr(u.operand()) + ", Boolean.TRUE)";
                    };
                    default -> throw error(u.line(), "unsupported operator " + u.op());
                };
            }
            case Update u -> {
                return update(u, true);
            }
            case Binary b -> {
                String test = comparison(b);
                if (test != null) {
                    return "JS.bool(" + test + ")";
                }
                return operator(b.op()) + "(" + expr(b.left()) + ", " + expr(b.right()) + ")";
            }
            case Logical l -> {
                String t = newTemp();
                String left = "(" + t + " = " + expr(l.left()) + ")";
                String right = expr(l.right());
                return switch (l.op()) {
                    case "&&" -> "(JS.truthy(" + left + ") ? (Object) " + right + " : " + t + ")";
                    case "||" -> "(JS.truthy(" + left + ") ? " + t + " : (Object) " + right + ")";
                    default -> "(JS.nullish(" + left + ") ? (Object) " + right + " : " + t + ")";
                };
            }
            case Assign a -> {
                return assign(a);
            }
            case Conditional c -> {
                return "(" + cond(c.test()) + " ? (Object) " + expr(c.then()) + " : (Object) " + expr(c.otherwise()) + ")";
            }
            case Call c -> {
                String args = list(c.args());
                String tail = args.isEmpty() ? "" : ", " + args;
                return switch (c.callee()) {
                    case Member m -> "JS.invoke(" + expr(m.object()) + ", " + quote(m.name()) + tail + ")";
                    case Index i -> "JS.invoke(" + expr(i.object()) + ", " + expr(i.index()) + tail + ")";
                    default -> "JS.call(" + expr(c.callee()) + tail + ")";
                };
            }
            case Chain c -> {
                Expr base = c.base();
                List<ChainOp> ops = c.ops();
                if (ops.get(0).kind() == 'c' && (base instanceof Member || base instanceof Index)) {
                    // In o.f?.() the call is on a property, so o is its this: make the property the first step.
                    ops = new ArrayList<>(ops);
                    if (base instanceof Member m) {
                        ops.add(0, new ChainOp('m', m.name(), null, null, false));
                        base = m.object();
                    } else {
                        Index ix = (Index) base;
                        ops.add(0, new ChainOp('i', null, ix.index(), null, false));
                        base = ix.object();
                    }
                }
                return chain(expr(base), ops, 0);
            }
            case New n -> {
                String args = list(n.args());
                return "JS.construct(" + expr(n.callee()) + (args.isEmpty() ? "" : ", " + args) + ")";
            }
            case Member m -> {
                return "JS.get(" + expr(m.object()) + ", " + quote(m.name()) + ")";
            }
            case Index i -> {
                return "JS.get(" + expr(i.object()) + ", " + expr(i.index()) + ")";
            }
            case Sequence s -> {
                String result = expr(s.exprs().get(s.exprs().size() - 1));
                for (int i = s.exprs().size() - 2; i >= 0; i--) {
                    result = "JS.second(" + expr(s.exprs().get(i)) + ", " + result + ")";
                }
                return result;
            }
        }
    }

    /**
     * Applies chain steps to {@code current}. A step written with {@code ?.} tests what it is applied to and, if that
     * is null or undefined, makes the whole rest of the chain undefined, so the remaining steps go inside the conditional.
     * A call that follows a property step is one operation, so the property's object becomes {@code this}.
     */
    private String chain(String current, List<ChainOp> ops, int i) {
        if (i == ops.size()) {
            return current;
        }
        ChainOp op = ops.get(i);
        boolean method = op.kind() != 'c' && i + 1 < ops.size() && ops.get(i + 1).kind() == 'c';
        if (method) {
            ChainOp call = ops.get(i + 1);
            String key = op.kind() == 'm' ? quote(op.name()) : expr(op.index());
            String args = list(call.args());
            String tail = args.isEmpty() ? "" : ", " + args;
            String object = newTemp();
            String function = newTemp();
            String receiver = op.optional() ? object : "(" + object + " = " + current + ")";
            String invoke = call.optional()
                    ? "(JS.nullish(" + function + " = JS.get(" + receiver + ", " + key + ")) ? JS.U : "
                            + chain("JS.callMethod(" + function + ", " + object + tail + ")", ops, i + 2) + ")"
                    : chain("JS.invoke(" + receiver + ", " + key + tail + ")", ops, i + 2);
            if (!op.optional()) {
                return invoke;
            }
            return "(JS.nullish(" + object + " = " + current + ") ? JS.U : " + invoke + ")";
        }
        String step;
        String subject = op.optional() ? newTemp() : null;
        String operand = subject != null ? subject : current;
        switch (op.kind()) {
            case 'm' -> step = "JS.get(" + operand + ", " + quote(op.name()) + ")";
            case 'i' -> step = "JS.get(" + operand + ", " + expr(op.index()) + ")";
            default -> {
                String args = list(op.args());
                step = "JS.call(" + operand + (args.isEmpty() ? "" : ", " + args) + ")";
            }
        }
        String rest = chain(step, ops, i + 1);
        return subject == null ? rest : "(JS.nullish(" + subject + " = " + current + ") ? JS.U : " + rest + ")";
    }

    private String list(List<Expr> exprs) {
        List<String> parts = new ArrayList<>();
        boolean spread = false;
        for (Expr e : exprs) {
            if (e instanceof Spread sp) {
                spread = true;
                parts.add("JS.spreadOf(" + expr(sp.value()) + ")");
            } else {
                parts.add(expr(e));
            }
        }
        // With a spread the arguments are built at run time, as one array that is passed as the varargs.
        return spread ? "JS.spread(" + String.join(", ", parts) + ")" : String.join(", ", parts);
    }

    private static String joinQuoted(List<String> strings) {
        List<String> parts = new ArrayList<>();
        for (String s : strings) {
            parts.add(quote(s));
        }
        return String.join(", ", parts);
    }

    private Var assignable(Ident id) {
        Var v = an.resolved.get(id);
        if (v == null) {
            throw error(id.line(), "cannot assign to " + id.name());
        }
        if (v.kind.equals("const")) {
            throw error(id.line(), "Assignment to constant variable '" + id.name() + "'");
        }
        if (v.kind.equals("this") || v.kind.equals("self")) {
            throw error(id.line(), "cannot assign to " + id.name());
        }
        return v;
    }

    private String update(Update u, boolean valueNeeded) {
        String op = u.op().equals("++") ? "JS.add" : "JS.sub";
        boolean postfix = !u.prefix() && valueNeeded;
        switch (u.target()) {
            case Ident id -> {
                Var v = assignable(id);
                if (!postfix) {
                    return write(v, op + "(" + read(v) + ", JS.ONE)");
                }
                String old = newTemp();
                return "JS.second(" + write(v, op + "(" + old + " = " + read(v) + ", JS.ONE)") + ", " + old + ")";
            }
            case Member m -> {
                return referenceUpdate(m.object(), quote(m.name()), op, "JS.ONE", postfix);
            }
            case Index i -> {
                return referenceUpdate(i.object(), expr(i.index()), op, "JS.ONE", postfix);
            }
            default -> throw error(u.line(), "invalid increment target");
        }
    }

    /** {@code o[k] = op(o[k], value)}, evaluating o and k once; yields the old value when {@code postfix}. */
    private String referenceUpdate(Expr object, String key, String op, String value, boolean postfix) {
        String o = newTemp();
        String k = newTemp();
        if (!postfix) {
            return "JS.set(" + o + " = " + expr(object) + ", " + k + " = " + key + ", " + op + "(JS.get(" + o + ", "
                    + k + "), " + value + "))";
        }
        String old = newTemp();
        return "JS.second(JS.set(" + o + " = " + expr(object) + ", " + k + " = " + key + ", " + op + "(" + old
                + " = JS.get(" + o + ", " + k + "), " + value + ")), " + old + ")";
    }

    private String assign(Assign a) {
        String op = a.op();
        switch (a.target()) {
            case Ident id -> {
                Var v = assignable(id);
                if (op.equals("=")) {
                    return write(v, named(a.value(), id.name()));
                }
                if (op.equals("&&=") || op.equals("||=") || op.equals("??=")) {
                    String test = switch (op) {
                        case "&&=" -> "JS.truthy(" + read(v) + ")";
                        case "||=" -> "!JS.truthy(" + read(v) + ")";
                        default -> "JS.nullish(" + read(v) + ")";
                    };
                    return "(" + test + " ? " + write(v, expr(a.value())) + " : " + read(v) + ")";
                }
                return write(v, operator(op.substring(0, op.length() - 1)) + "(" + read(v) + ", " + expr(a.value()) + ")");
            }
            case Member m -> {
                return assignReference(a, m.object(), quote(m.name()));
            }
            case Index i -> {
                return assignReference(a, i.object(), expr(i.index()));
            }
            default -> throw error(a.line(), "invalid assignment target");
        }
    }

    private String assignReference(Assign a, Expr object, String key) {
        if (a.op().equals("=")) {
            return "JS.set(" + expr(object) + ", " + key + ", " + expr(a.value()) + ")";
        }
        if (a.op().equals("&&=") || a.op().equals("||=") || a.op().equals("??=")) {
            throw error(a.line(), "logical assignment is only supported on plain variables");
        }
        String op = operator(a.op().substring(0, a.op().length() - 1));
        return referenceUpdate(object, key, op, expr(a.value()), false);
    }

    private JsException error(int line, String message) {
        return new JsException(file, line, message);
    }
}
