package duke.js;

import duke.compiler.image.ElfWriter;
import duke.compiler.image.Image;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * {@code jsc program.js --output program} compiles JavaScript to a static x86-64 Linux executable.
 * {@code jsc --java DIR a.js b.js ...} instead translates each module to a Java class in DIR, plus
 * a {@code Boot} entry point that dukec uses to put them in the kernel.
 */
public final class Main {

    private Main() {
    }

    public static void main(String[] args) throws IOException {
        if (args.length > 0 && args[0].equals("--java")) {
            javaMain(args);
            return;
        }
        Path input = null;
        Path output = null;
        for (int i = 0; i < args.length; i++) {
            if (args[i].equals("--output") || args[i].equals("-o")) {
                if (++i == args.length) {
                    usage("--output needs a value");
                }
                output = Path.of(args[i]);
            } else if (input == null && !args[i].startsWith("-")) {
                input = Path.of(args[i]);
            } else {
                usage("unknown argument " + args[i]);
            }
        }
        if (input == null || output == null) {
            usage("an input file and --output are required");
        }
        byte[] elf;
        try {
            elf = compile(input.toString(), Files.readString(input));
        } catch (JsException e) {
            System.err.println("jsc: error: " + e.getMessage());
            System.exit(1);
            return;
        }
        Files.write(output, elf);
        if (!output.toFile().setExecutable(true)) {
            System.err.println("jsc: warning: could not mark " + output + " executable");
        }
    }

    /** Compiles {@code source} (named {@code file} in errors) together with the runtime prelude. */
    public static byte[] compile(String file, String source) throws IOException {
        List<Node.Stmt> prelude = new Parser("<prelude>", prelude()).parseProgram();
        List<Node.Stmt> program = new Parser(file, source).parseProgram();
        Analyzer analyzer = new Analyzer(file, prelude, program);
        Image image = new CodeGen(file, analyzer).generate(prelude, program);
        // Text starts one page in, so the headers' page lands exactly at BASE.
        Image.Linked linked = image.link(CodeGen.BASE + Image.PAGE);
        return ElfWriter.write(linked, linked.address("_start"), true);
    }

    private static void javaMain(String[] args) throws IOException {
        if (args.length < 2) {
            usage("--java needs an output directory");
        }
        Path dir = Path.of(args[1]);
        List<Path> inputs = new ArrayList<>();
        for (int i = 2; i < args.length; i++) {
            inputs.add(Path.of(args[i]));
        }
        Map<String, String> sources = new LinkedHashMap<>();
        for (Path input : inputs) {
            sources.put(input.toString(), Files.readString(input));
        }
        try {
            Files.createDirectories(dir.resolve("duke/js/gen"));
            for (Map.Entry<String, String> e : translateAll(sources).entrySet()) {
                Files.writeString(dir.resolve("duke/js/gen/" + e.getKey() + ".java"), e.getValue());
            }
        } catch (JsException e) {
            System.err.println("jsc: error: " + e.getMessage());
            System.exit(1);
        }
    }

    /**
     * Translates modules (path to source) into Java: one class per module, a {@code Modules} class that
     * runs them in order, and {@code Boot}, the kernel's entry point once JS is part of the image.
     * Returns class name to Java source.
     */
    public static Map<String, String> translateAll(Map<String, String> modules) {
        Map<String, String> classes = new LinkedHashMap<>();
        StringBuilder init = new StringBuilder();
        for (Map.Entry<String, String> module : modules.entrySet()) {
            String className = className(module.getKey());
            if (classes.containsKey(className) || className.equals("Modules") || className.equals("Boot")) {
                throw new JsException(module.getKey(), 1, "another module is already called " + className);
            }
            classes.put(className, translate(module.getKey(), module.getValue(), className));
            init.append("        ").append(className).append(".run();\n");
        }
        classes.put("Modules", "package " + JavaGen.PACKAGE + ";\n\n/** Generated by jsc: runs every JavaScript module. */\n"
                + "public final class Modules {\n\n    private Modules() {\n    }\n\n    public static void init() {\n"
                + init + "    }\n}\n");
        classes.put("Boot", "package " + JavaGen.PACKAGE + ";\n\nimport duke.kernel.Kernel;\n\n"
                + "/** Generated by jsc: the kernel's entry point when JavaScript modules are part of the image. */\n"
                + "public final class Boot {\n\n    private Boot() {\n    }\n\n    public static void main() {\n"
                + "        Kernel.beforeShell = () -> Modules.init();\n        Kernel.main();\n    }\n}\n");
        return classes;
    }

    /** Translates one JavaScript module to the source of the Java class {@code className}. */
    public static String translate(String file, String source, String className) {
        List<Node.Stmt> program = new Parser(file, source).parseProgram();
        Analyzer analyzer = new Analyzer(file, List.of(), program, JavaGen.GLOBALS);
        return new JavaGen(file, analyzer, className).generate(program);
    }

    /** {@code fs-tools.js} becomes {@code FsTools}. */
    static String className(String path) {
        String base = Path.of(path).getFileName().toString().replaceAll("\\.js$", "");
        StringBuilder sb = new StringBuilder();
        boolean upper = true;
        for (char c : base.toCharArray()) {
            if (Character.isLetterOrDigit(c)) {
                sb.append(upper ? Character.toUpperCase(c) : c);
                upper = false;
            } else {
                upper = true;
            }
        }
        return Character.isDigit(sb.charAt(0)) ? "M" + sb : sb.toString();
    }

    private static String prelude() throws IOException {
        try (InputStream in = Main.class.getResourceAsStream("prelude.js")) {
            if (in == null) {
                throw new IOException("prelude.js is missing from the jsc jar");
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static void usage(String problem) {
        System.err.println("jsc: " + problem);
        System.err.println("usage: jsc program.js --output program");
        System.err.println("       jsc --java DIR module.js...");
        System.exit(2);
    }
}
