var a = [5, 3, 8, 1];
console.log(a, a.length, a[0], a[3], a[4]);
a.push(9); a.push(2, 7);
console.log(a, a.pop(), a.length);
console.log(a.shift(), a);
a.unshift(0);
console.log(a, a.indexOf(8), a.indexOf(99), a.includes(3), a.includes(4));
console.log(a.slice(1, 3), a.slice(-2), a.slice(), a.slice(0, 2).concat([100], 300));
console.log(a.map((x) => x * 2), a.filter((x) => x > 3), a.reduce((s, x) => s + x, 0), a.reduce((s, x) => s + x));
console.log(a.some((x) => x > 8), a.every((x) => x >= 0), a.find((x) => x > 5), a.findIndex((x) => x > 5), a.find((x) => x > 50));
console.log([3, 1, 2].sort(), [10, 9, 1, 100].sort(), [10, 9, 1, 100].sort((x, y) => x - y), [3, 1, 2].reverse());
console.log(["b", "a", "c"].sort(), [1, 2, 3].join("-"), [1, [2, 3]].join(";"), [null, undefined, 1].join());
var grow = [];
for (var i = 0; i < 1000; i++) grow.push(i * i);
console.log(grow.length, grow[999], grow.reduce((s, x) => s + x, 0));
grow.length = 3;
console.log(grow);
grow[3] = 1;
console.log(grow, grow.length);
var seen = [];
[10, 20, 30].forEach((x, i) => seen.push(i + ":" + x));
console.log(seen);
for (var x of [1, 2, 3]) { if (x === 2) continue; console.log("of", x); }
var matrix = [[1, 2], [3, 4]];
console.log(matrix.map((row) => row.map((v) => v * v)));
console.log([1, 2, 3].map(String), ["1", "2"].map(Number));
var big = [];
for (var n = 0; n < 5000; n++) big.push((n * 7919) % 1009);
big.sort((p, q) => p - q);
console.log(big[0], big[2500], big[4999]);
console.log(Math.max(1, 5, 3), Math.min(4, 2, 8), Math.abs(-4), Math.floor(7));
