var o = { a: 1, b: "two", c: [3, 4], d: { e: 5 } };
console.log(o);
console.log(o.a, o["b"], o.c[1], o.d.e, o.missing);
o.a = 10; o["new"] = "added"; o.d.e += 1; o.c[0]++;
console.log(o);
var key = "dyn";
o[key + "amic"] = 1;
console.log(Object.keys(o), Object.values({ x: 1, y: 2 }));
var empty = {};
console.log(empty, [], [[]], [{}], { a: {} });
console.log({ "needs-quote": 1, valid_id: 2 });
var nested = { l1: { l2: { l3: { l4: "deep" } } }, arr: [[1, [2, [3, [4]]]]] };
console.log(nested);
var short = 1, name = "n";
console.log({ short, name });
var counts = {};
var words = ["a", "b", "a", "c", "b", "a"];
for (var w of words) counts[w] = (counts[w] || 0) + 1;
console.log(counts);
var grid = [];
for (var r = 0; r < 3; r++) { grid.push([]); for (var q = 0; q < 3; q++) grid[r].push(r * 3 + q); }
console.log(grid, grid[1][2]);
console.log({ a: 1, b: { c: [1, 2, { d: 3 }] } }, "text", 42, [1, "two", [3]]);
var long = { alpha: "aaaaaaaaaaaaaaaa", beta: "bbbbbbbbbbbbbbbbb", gamma: "cccccccccccccccc", delta: "dddddddddddd" };
console.log(long);
console.log(Array.isArray([]), Array.isArray({}), Number.isInteger(5), Number.isInteger("5"));
var f = function () {};
f.tag = "on a function";
console.log(f.tag, f.other);
