var s = "hello, world";
console.log(s, s.length, s[0], s[4], s[100], s.charAt(1), s.charCodeAt(1));
console.log(s.indexOf("o"), s.indexOf("o", 5), s.indexOf("xyz"), s.includes("wor"), s.startsWith("hell"), s.endsWith("ld"));
console.log(s.slice(7), s.slice(-5), s.slice(2, -3), s.substring(3, 6), s.substring(6, 3));
console.log(s.toUpperCase(), "MiXeD".toLowerCase(), "  padded \t".trim() + "|");
console.log("a,b,,c".split(","), "abc".split(""), "no commas".split(","), "a--b--c".split("--"));
console.log("ab".repeat(3), "7".padStart(3, "0"), "7".padEnd(3, "."), "abc".concat("def"));
console.log("a" + 1, 1 + "a", "x" + null, "x" + undefined, "x" + true, 1 + 2 + "3", "1" + 2 + 3);
console.log(`template ${1 + 2} and ${"nested " + `${s.length}`}!`);
console.log("abc" < "abd", "abc" < "ab", "b" > "a", "a" === "a", "a" + "b" === "ab", "ab" !== "a" + "b");
console.log("10" - 3, "6" * "7", +"42", Number("-17"), parseInt("123abc"), String(77), String(-5));
var built = "";
for (var i = 0; i < 20; i++) built += i % 10;
console.log(built, built.length);
console.log("it's", 'say "hi"', ["it's", 'say "hi"', "plain", "new\nline"]);
console.log(String.fromCharCode(72) + String.fromCharCode(105));
var parts = [];
for (var c of "xyz") parts.push(c + c);
console.log(parts.join("-"));
console.log("" + [1, 2, 3], "" + {}, [] + "", [1, [2, 3]] + "");
