import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Converts an 8x16 BDF font (Spleen, BSD-2-Clause) into kernel/src/duke/kernel/Font.java:
 * {@code java tools/GenerateFont.java spleen-8x16.bdf LICENSE}. Code points 0-255, 16 row bytes
 * each, packed into a string literal so the glyphs are image data with tiny bytecode.
 */
public class GenerateFont {

    public static void main(String[] args) throws Exception {
        List<String> lines = Files.readAllLines(Path.of(args[0]));
        String license = Files.readString(Path.of(args[1])).strip();
        char[] glyphs = new char[256 * 16];
        int encoding = -1;
        for (int i = 0; i < lines.size(); i++) {
            String line = lines.get(i);
            if (line.startsWith("ENCODING ")) {
                encoding = Integer.parseInt(line.substring(9).trim());
            } else if (line.startsWith("BBX ") && !line.equals("BBX 8 16 0 -4")) {
                throw new IllegalStateException("glyph " + encoding + " isn't a full 8x16 cell: " + line);
            } else if (line.equals("BITMAP") && encoding >= 0 && encoding < 256) {
                for (int row = 0; row < 16; row++) {
                    glyphs[encoding * 16 + row] = (char) Integer.parseInt(lines.get(i + 1 + row).trim(), 16);
                }
            }
        }
        StringBuilder src = new StringBuilder("package duke.kernel;\n\n/*\n * Generated by tools/GenerateFont.java from the Spleen 8x16 font, whose license follows.\n *\n");
        for (String l : license.split("\n")) {
            src.append(l.isBlank() ? " *" : " * " + l).append('\n');
        }
        src.append(" */\n\n/** 8x16 glyphs for code points 0-255: 16 row bytes each, most significant bit leftmost. */\n");
        src.append("final class Font {\n\n    static final int WIDTH = 8;\n    static final int HEIGHT = 16;\n\n    static final String GLYPHS =\n");
        for (int g = 0; g < 256; g++) {
            src.append("            \"");
            for (int row = 0; row < 16; row++) {
                src.append(escape(glyphs[g * 16 + row]));
            }
            src.append(g == 255 ? "\";\n" : "\" +\n");
        }
        src.append("\n    private Font() {\n    }\n}\n");
        Files.writeString(Path.of("kernel/src/duke/kernel/Font.java"), src);
    }

    /**
     * javac turns unicode escapes into characters before it tokenizes, so the four that would end
     * or break a string literal need ordinary escapes instead.
     */
    static String escape(char c) {
        return switch (c) {
            case '\n' -> "\\n";
            case '\r' -> "\\r";
            case '"' -> "\\\"";
            case '\\' -> "\\\\";
            default -> String.format("\\u%04x", (int) c);
        };
    }
}
